//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinnacleCodingConvention.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinnacleCodingConvention.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Variables....
        /// </summary>
        internal static string ClassVariablesRegion {
            get {
                return ResourceManager.GetString("ClassVariablesRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant(s)....
        /// </summary>
        internal static string ConstantsRegion {
            get {
                return ResourceManager.GetString("ConstantsRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor(s)....
        /// </summary>
        internal static string ConstructorsRegion {
            get {
                return ResourceManager.GetString("ConstructorsRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destructor.
        /// </summary>
        internal static string DestructorRegion {
            get {
                return ResourceManager.GetString("DestructorRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods....
        /// </summary>
        internal static string MethodsRegion {
            get {
                return ResourceManager.GetString("MethodsRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties....
        /// </summary>
        internal static string PropertiesRegion {
            get {
                return ResourceManager.GetString("PropertiesRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove region.
        /// </summary>
        internal static string RemoveRegion {
            get {
                return ResourceManager.GetString("RemoveRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See output for more information.
        /// </summary>
        internal static string SeeOutputForMoreInformation {
            get {
                return ResourceManager.GetString("SeeOutputForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests....
        /// </summary>
        internal static string TestsRegion {
            get {
                return ResourceManager.GetString("TestsRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
