// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PinnacleCodingConvention
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PinnacleCodingConventionPackageString = "2aef4ddf-562d-4264-9929-24f3be06c921";
        public static Guid PinnacleCodingConventionPackage = new Guid(PinnacleCodingConventionPackageString);

        public const string PinnacleCodingConventionPackageCmdSetString = "a35bce14-852c-484e-a8c0-88371dbc25ad";
        public static Guid PinnacleCodingConventionPackageCmdSet = new Guid(PinnacleCodingConventionPackageCmdSetString);

        public const string IconString = "6604656d-6c88-457b-8788-1aa26288582e";
        public static Guid Icon = new Guid(IconString);

        public const string PinnacleCodingConventionOutputPaneString = "baf6f569-4d9d-4d08-9cf9-6b98cd7a47b1";
        public static Guid PinnacleCodingConventionOutputPane = new Guid(PinnacleCodingConventionOutputPaneString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EditorContextMenuGroup = 0x1020;
        public const int CleanUpCommandId = 0x0100;
        public const int commandIcon1 = 0x0001;
    }
}