// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PinnacleCodingConvention
{
    internal sealed partial class Vsix
    {
        public const string Id = "51680286-a796-4437-96c7-9cbdd354ed2f";
        public const string Name = "Pinnacle Coding Convention";
        public const string Description = @"This project is about to ensure and automate some coding conventions in the Pinnacle solution. 
It helps developers to avoid some tedious NW in code review, e.g. A-Z order, missing regions, regions not matched.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "KhanhVu";
        public const string Tags = "Coding Standard, Cleanup, PinnacleDMS, Tools";
    }
}
